version: '3'
services:
  athena:
    image: athenascheduler/athena
    ports:
      - "5000:5000"
    environment:
      - "ATHENA_CONNECTION_STRING=Server=db;User ID=postgres;Database=postgres"
    env_file:
      - auth-keys.env
    depends_on:
      - db
  db:
    image: athenascheduler/db
